import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Main from "@/components/Main";
import { CartProvider } from "@/utilities/context/CartContext";
import "./globals.css";
import "./style.css";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import { ApolloWrapper } from "@/lib/ApolloWrapper";
import { Toaster } from "sonner";
import 'react-loading-skeleton/dist/skeleton.css';
import Header from "@/components/header/Header";
import BodyDataPage from "./BodyDataPage";
import Footer from "@/components/footer/Footer";
import { getInstance } from "@/lib/instance";


const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const dalamoa = localFont({
  src: "../../assets/fonts/DalaMoaBold.otf",
  variable: "--font-dalamoa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string};
}>) {
  const instance = await getInstance()
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const stylesToaster = {
    style: {
      backgroundColor: "var(--black)",
      color: "#fff",
      borderColor: "var(--black)",
      alignItems: "center",
      display: "flex",
      fontSize: "14px",
      maxWidth: "356px"
    }
  };

  return (
    <html lang="es" className={`${dalamoa.variable} ${poppins.variable}`}>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <ApolloWrapper>
        <NextIntlClientProvider>
          <CartProvider>
            <body className={`bg-(--background) antialiased`}>
              <BodyDataPage />
              <Header />
              <Main>{children}</Main>
              <Footer />
              <Toaster 
                position="bottom-center"
                toastOptions={stylesToaster}
                icons={{
                  success: <i className="icon-check_circle text-lg text-white" />,
                  error: <i className="icon-warning text-lg text-white" />,
                  warning: <i className="icon-alert text-lg text-white" />,
                  info: <i className="icon-info text-lg text-white" />,
                }}
              />
              <div id="portal-root"></div>
            </body>
          </CartProvider>
        </NextIntlClientProvider>
      </ApolloWrapper>
    </html>
  );
}
